pls-website/home/urls.py
from django.conf.urls import url, include
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('quiz2', views.quiz, name = 'quiz'),
    path('scenario', views.scenario, name = 'scenario'),
    path('quiz', views.quiz2, name='quiz2'),
    path('thankyou', views.resultsPage, name='resultsPage'),
    path('moderator', views.moderator, name='moderator'),
    path('info', views.info, name='info'),
    path('feedback', views.feedback, name='feedback'),
    path('reattempt', views.reattempt, name='reattempt'),
    path('revisit', views.revisit, name='revisit'),
    path('preresults', views.preresults, name='preresults'),
    path('comeback/<pk>', views.comeback, name='comeback'),
    path('view_feedback', views.view_feedback, name='view_feedback'),
    path('', views.home, name='home')
]

pls-website/pls/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

pls-website/home/models.py
from django.db import models

# Create your models here.

pls-website/home/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.utils.safestring import mark_safe
from ibmcloudant.cloudant_v1 import CloudantV1, Document
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
import random, string
import requests

def choose_category():
    value = '''

    <div class="received-chats old-chats"><div class="received-chats-img"><img src="https://data.cometchat.com/assets/images/avatars/captainamerica.png" alt="Avatar" class="avatar"></div>
    <div class="received-msg"><div class="received-msg-inbox">

    <p>
    <span id="message-sender-id">PLS bot</span><br>
    Welcome to IBM's PLS bot.
    </p>

    </div></div></div>

    <div class="received-chats old-chats"><div class="received-chats-img"><img src="https://data.cometchat.com/assets/images/avatars/captainamerica.png" alt="Avatar" class="avatar"></div>
    <div class="received-msg"><div class="received-msg-inbox">

    <p>
    <span id="message-sender-id">PLS bot</span><br>
    Please select the category to continue <br><br>

    <input type="checkbox" name="1" value="1" id='1'>
    <label style="color:rgb(100,100,100);font-weight:normal;" for="1">Outdoor Classroom Experience</label><br>
    <input type="checkbox" name="2" value="2">
    <label style="color:rgb(100,100,100);font-weight:normal;" for="2">Under Lockdown</label><br>
    <input type="checkbox" name="3" value="3">
    <label style="color:rgb(100,100,100);font-weight:normal;" for="3">Rockclimbing</label><br><br>

    <button style="color:rgb(225,225,225);font-weight:normal;" class="login-btn" type="submit">Next</button>
    </p>
    </div></div></div>

    '''
    return value
def get_data():

    # CLOUDANT_USERNAME="apikey-v2-1mfs4kqo2nmnc2sdtgp9ji8myznbgm6mivk0o93pfopt"
    # CLOUDANT_PASSWORD="f70c9a73c52d287d3271ddc3dba6a30a"
    #
    # authenticator = IAMAuthenticator("C8J8TcTL_T9YlMtyA6itWueAqAdkgGXbwOc8RA2omfCd")
    # service = CloudantV1(authenticator=authenticator)
    # service.set_service_url("https://apikey-v2-1mfs4kqo2nmnc2sdtgp9ji8myznbgm6mivk0o93pfopt:f70c9a73c52d287d3271ddc3dba6a30a@dc1a5ff5-996b-475c-8b7e-da87f4bf33a3-bluemix.cloudantnosqldb.appdomain.cloud")
    # response = service.get_server_information().get_result()
    #
    # response = service.get_document(db='qdata', doc_id='001').get_result()

    url = "https://api.npoint.io/c4b4edd3640ed8357987"

    r = requests.get(url)
    data = r.json()

    return data #response['data']
def get_scene():
    scene = {
    '1':'Outdoor Classroom Experience',
    '2':'Under Lockdown',
    '3':'Rockclimbing'
    }
    return scene

def home(request):
    return render(request, 'home/home.html')

def info(request):
    request.session['responses'] = list('')
    request.session['unanswered'] = list('')
    request.session['ansd'] = list('')
    request.session['ansd2'] = list('')
    return render(request, 'home/info.html')

def scenario(request):
    if request.method == 'POST':
        return render(request, 'home/quiz.html')

    return render(request, 'home/scenario.html')

def resultsPage(request):
    responses = list(request.session['responses'])
    responses = [i for i in responses if i != ['']]
    responses = [i for i in responses if i != ['jump']]
    responses = [i for i in responses if i != ['exit']]

    res = [sum(i)/len(responses) for i in zip(*responses)]

    ansd = list(request.session['ansd'])
    ansd = [i for i in ansd if i != ['']]
    ansd = [i for i in ansd if i != ['jump']]
    ansd = [i for i in ansd if i != ['exit']]

    tlist = []
    data = get_data()

    results = request.session['results']
    n_s = len(results) # no of scenarios selected

    for x in results:
        q_data = data[x]
        n = len(q_data)
        for y in range(1, n+1):
            tlist.append([x, y])

    x, y = tlist, ansd

    for i in x[:]:
      if i in y:
          x.remove(i)
          y.remove(i)

    unansd = tlist

    # code = ' you have not answered the following <br> '

    tp = []
    un_sec = {} #unanswered sections
    for i in unansd:
        tp.append(int(i[0]))

    tp = list(set(tp))

    ##### finding lengths of tp
    data = get_data()
    leng = {}
    for i in tp:
        n = len(data[str(i)])
        leng[str(i)] = n
    #####

    for i in tp:
        # i is the section number
        un_sec[str(i)] = []
        for j in unansd:
            if j[0] == str(i):
                un_sec[str(i)].append(j[1])

    uns_p = {}
    for i in tp:
        un_p = len(un_sec[str(i)]) / float(leng[str(i)])
        un_p = int(un_p * 100)
        uns_p[str(i)] = un_p

    print(uns_p)

    ##### Generarting code #####

    code = '<br><br><br>'

    for i in tp:
        code = code + 'you have not answered ' + str(uns_p[str(i)]) + '% of section ' + str(str(i)) + '. Revisit? <input type="submit" name="action" value="'+str(str(i))+'"> <br>'
    code = code + '<br><br>'

    return render(request, 'home/results.html', {'V':int(res[0]), 'A':int(res[1]), 'K':int(res[2]), 'code':mark_safe(code)})

# Create your views here.
def quiz(request):

    if request.method == 'POST':
        results = list(request.POST.keys())
        results = results[1:]
        n_s = len(results)
        request.session['results'] = results
        request.session['s'] = 0
        q_data = get_data()
        n = len(q_data)
        request.session['c'] = 1
        progress = 0
        scene = get_scene()[(results[0])]

        return render(request, 'home/scenario.html', {'scene':scene, 's':int(1)})
    else:
        progress = 0
        request.session['c'] = 0
        code = choose_category()

    return render(request, 'home/quiz.html', {'content': mark_safe(code), 'progress':progress, 'q':'PLS bot'})

def quiz2(request):
    try:
        if request.POST['action']:
            if request.POST['action'] == 'jump':
                code =  ''
                request.session['s'] += 1
                request.session['c'] = 1

                if (s+1) == n_s:
                    return render(request, 'home/dummy.html')

                s = request.session['s']
                scene = get_scene()[(results[s])]
                return render(request, 'home/scenario.html', {'scene':scene, 's':int(s+1)})

            elif request.POST['action'] == 'exit':
                return render(request, 'home/dummy.html')
    except:
        a = 0

    s = int(request.session['s'])
    c = request.session['c']
    responses = list(request.session['responses'])
    results = list(request.session['results'])

    try:

        answers = list(request.POST.values())
        answers = answers[1:]

        if len(answers) != 1:
            answers = [int(float(i)) for i in answers]
            if answers[0] == answers[1] == answers[2] == 33:
                unans = list(request.session['unanswered'])
                li = [s, int(int(c)-1)]
                unans.append(li)
                request.session['unanswered'] = unans
            else:
                ansd = list(request.session['ansd'])
                li = [str(results[s]), int(int(c)-1)]####################!
                ansd.append(li)
                request.session['ansd'] = ansd

                ansd2 = list(request.session['ansd2'])
                li = [str(results[s]), int(int(c)-1)]####################!
                ansd2.append(li)
                request.session['ansd2'] = ansd2

        responses.append(answers)
        request.session['responses'] = responses
    except:
        v=0
    n_s = len(results)

    if s == n_s:
        return render(request, 'home/dummy.html')
    data = get_data()
    q_data = data[(results[s])]

    ansd2 = list(request.session['ansd2'])
    print(ansd2)

    n = len(q_data)
    n_a = len(ansd2)
    n_u = c - n_a - 1
    pa = n_a * 100 / n
    pu = n_u * 100 / n
     ### c questions are done
    ### make a code for c 'th question
    progress = int((c-1)/(n)*100)
    progress2 = int((s)*100/n_s)

    if n < c:
        code =  ''
        request.session['s'] += 1
        request.session['c'] = 1
        request.session['ansd2'] = list('')

        if (s+1) == n_s:
            return render(request, 'home/dummy.html')

        s = request.session['s']
        scene = get_scene()[(results[s])]
        return render(request, 'home/scenario.html', {'scene':scene, 's':int(s+1)})
    else:
        code = '''
                    <div class="">
                    <div class=""><div class="">
                    <p>
                    <br>''' + q_data[str(int(c))]['q'] + '''
                    <br><br>
                    1. ''' + q_data[str(int(c))]['V'] + '''<br>

                    <div class="slider one slide-option">
                      <div class="slide">
                        <div class="control">
                          <div class="switch">
                              <input type="number" class="value_in hidden" value="0" name="charity_one" min="0" max="100">
                          </div>
                          </div>
                      </div>
                      <br>

                    2. ''' + q_data[str(int(c))]['A'] + '''<br>

                    <div class="slider two">
                      <div class="slide">
                         <div class="control">
                           <div class="switch">
                              <input type="number" class="value_in hidden" value="0" name="charity_two" min="0" max="100">
                          </div>
                          </div>
                      </div>
                      <br>

                    3. ''' + q_data[str(int(c))]['K'] + '''<br>

                    <div class="slider four">
                    <div class="slide">
                        <div class="control">
                        <div class="switch">
                            <input type="number" class="value_in hidden" value="0" name="charity_four" min="0" max="100">
                        </div>
                    </div>

pls-website/home/templates/home/comeback.html
{{pc}}

pls-website/home/templates/home/preresults.html
{% load static %}

<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> jQuery Chat Application </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto&amp;display=swap">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <style>
    body {
      background-image: url('static/home/img/background.png');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    </style>
    <style media="screen">

      *{
          margin: 0;
          padding: 0;
      }
      .rate {
          float: left;
          height: 46px;
          padding: 0 10px;
      }
      .rate:not(:checked) > input {
          position:absolute;
          top:-9999px;
      }
      .rate:not(:checked) > label {
          float:right;
          width:1em;
          overflow:hidden;
          white-space:nowrap;
          cursor:pointer;
          font-size:30px;
          color:#ccc;
      }
      .rate:not(:checked) > label:before {
          content: '★ ';
      }
      .rate > input:checked ~ label {
          color: #ffc700;
      }
      .rate:not(:checked) > label:hover,
      .rate:not(:checked) > label:hover ~ label {
          color: #deb217;
      }
      .rate > input:checked + label:hover,
      .rate > input:checked + label:hover ~ label,
      .rate > input:checked ~ label:hover,
      .rate > input:checked ~ label:hover ~ label,
      .rate > label:hover ~ input:checked ~ label {
          color: #c59b08;
      }

      /* Modified from: https://github.com/mukulkant/Star-rating-using-pure-css */

    </style>

</head>
<body>
    <div class="chat-app-wrapper">
        <nav>
            <div class="nav-left-section">
                <span id="title">Preffered learning style determination</span>
            </div>
        </nav>

        <div class="chat">
          <br>

          <br><br>
            <div class="container">
                <div class="msg-header">
                    <div class="active">
                        <h5>
                          Results!
                        </h5>
                    </div>
                </div>

                <div class="chat-page">
                    <div class="msg-inbox">
                        <div class="chats" id="chats">
                            <div class="msg-page" id="msg-page">
                                <div class="loading-message-container" id="loading-message-container" style="display: none;">
                                    <div class="spinner">
                                            <svg width="100" height="100" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#003">
                                                <g fill="none" fill-rule="evenodd">
                                                  <g transform="translate(1 1)" stroke-width="2">
                                                    <circle stroke-opacity=".5" cx="18" cy="18" r="18"></circle>
                                                    <path d="M36 18c0-9.94-8.06-18-18-18">
                                                      <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite"></animateTransform>
                                                    </path>
                                                  </g>
                                                </g>
                                              </svg>
                                    </div>
                                </div>


                                <div>
                                    <div id="group-message-holder" style="">

<!--  ############################################# -->


<!--  ############################################# -->
<br><br><br>
<center>

<div class="" style="width:60%;">

  <form class="" action="{% url 'home:preresults' %}" method="POST">
    {% csrf_token %}

    {{ code }}
  </form>

  <form class="" action="{% url 'home:resultsPage' %}" method="POST">
    {% csrf_token %}

    {{ continue }}
  </form>


</div>


<!--  ############################################# -->

                </div>
                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="msg-bottom">
                            <form class="message-form" id="message-form">
                                <div class="input-group">
                                    <input type="text" id="input-text" class="form-control message-input" placeholder="Type something" required="">
                                    <div id="send-message-spinner" class="spinner" style="display: none;">
                                            <svg width="30" height="30" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#003">
                                                <g fill="none" fill-rule="evenodd">
                                                  <g transform="translate(1 1)" stroke-width="2">
                                                    <circle stroke-opacity=".5" cx="18" cy="18" r="18"></circle>
                                                    <path d="M36 18c0-9.94-8.06-18-18-18">
                                                      <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite"></animateTransform>
                                                    </path>
                                                  </g>
                                                </g>
                                              </svg>
                                    </div>
                                    <input id="loggedInUID" type="hidden">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <br><br>

            </div>
        </div>
    </div>



<!-- Dummy scripts -->
<!-- <script src="{% static 'home/js/chatService-dummy.js' %}"></script>
<script src="{% static 'home/js/script-dummy.js' %}"></script> -->


</body></html>

pls-website/home/templates/home/quiz2.html
{% load static %}

<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> jQuery Chat Application </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Abril+Fatface&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto&amp;display=swap">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <style>
    body {
      background-image: url('static/home/img/background.png');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    </style>

    <style media="screen">
      div.sliders {
      margin: 20px auto;
      background-color: #000000;
      width: 50%;
      padding: 20px;
      }
      .slide-option {
        display: flex;
        flex-direction: row;
      }
      div.slider {
      display: block;
      width: 100%;
      margin: 20px auto;
      background-color: #ffffff;
      height: 20px;
      border: 1px solid rgb(200,200,200);
      }

      div.slide {
      width: 33%;
      height: 100%;
      background: #1663AC;
      position: relative;
      }

      div.control {
      width: 15px;
      height: 15px;
      border-radius: 50%;
      // padding: 40px;
      background: #7C71A1;
      position: absolute;
      right: -7px;
      top: 50%;
      margin-top: -7px;
      cursor: pointer;
      }
      .switch{
      position:relative;
      left:-100px;
      }

      .hidden{
      display:none;
      }
    </style>
    <script type="text/javascript">
      $(document).ready(function() {
        slider = new Slider();
      });

      var Slider = (function() {

        var Slider = function() {

          this.initialise();
        }

        Slider.prototype = {

          initialise: function() {
            this.vars();
            this.setup();
            this.slideEvent();
          },

          vars: function() {
            // vars
            _this = this;
            this.container = $('.sliders');
            this.slider = $('.slider');
            this.slide = $('.slide');
            this.controls = $('.control');
            this.value = $('.value');
            this.value_in = $('.value_in');
            this.totalPercentage = 100;
          },

          setup: function() {
            // set equal width depending on how many sliders there are when initalised
            var counter = 0;
            this.slide.each(function() {
              counter++;
            });

            var initWidth = Math.round(this.totalPercentage / counter);

           this.slide.width(initWidth + '%');
           this.slide.attr('data-percent', initWidth + '%');
           this.value.text(initWidth + '%');
           this.value_in.val(initWidth);
          },

          getPercentWidth: function(target) {
            // get percentage of current width
            target.attr('data-percent', (100 * parseInt(target.css('width')) / parseInt(target.parent().css('width'))));
          },

          slideEvent: function() {
            // listen for mouse down on the controls
            this.controls.on('mousedown', function(event) {
              this.slideDrag(event);
            }.bind(this));
          },

          slideDrag: function(event) {
            event.preventDefault();

            this.target = $(event.target);
            this.prevMousePos = 0;

            this.target.parent().addClass('active');
            // listen mousemove and mouseup events on the document: only if the mousedown happend on one of the controls
            $(document).on('mousemove', this.slideMove);
            $(document).on('mouseup', this.slideEnd);
          },

          slideMove: function() {
            _this.mousePos = event.pageX;
            _this.amount = [];

            // get info on widths, offsets and positions
            var offset = _this.slider.offset().left;
            var sliderWidth = _this.slider.width();
            var posX = Math.min(Math.max(0, _this.mousePos - offset), sliderWidth);

            // checks direction
            if (_this.mousePos < _this.prevMousePos)  {
              _this.direction = 'left';
            } else {
              _this.direction = 'right';
            }

            //console.log(_this.direction);

            // update mouse position
            _this.prevMousePos = _this.mousePos;

            // set new width of the active slider
            _this.target.parent().width(posX / sliderWidth * 100 + '%');
            _this.calcPercent();

          },

          calcPercent: function() {
            var totalWidth = 0;
            var sliderLength = 0;
            var leftoverAmount = 0;

            // loop through each slide
            _this.slide.each(function() {

              sliderLength++;
              _this.getPercentWidth($(this));

              if ($(this).hasClass('active')) {
                // set active percentage
                _this.active = parseInt($(this).attr('data-percent')).toFixed(0);


              } else {

                // add non active widths into an array

                _this.amount.push(parseInt($(this).attr('data-percent')).toFixed(0));
              }

             //totalWidth += parseFloat($(this).attr('data-percent'));

            });

            // find out the leftover amount
            leftoverAmount = _this.totalPercentage - _this.active;
            _this.nonActiveAmount = 0;
            $.each(_this.amount, function() {

             _this.nonActiveAmount += parseInt(this) ;
            });

            var x = leftoverAmount / 100;
            var y = _this.nonActiveAmount / 100;
            var z = _this.active;


            _this.slide.each(function() {

              if (!$(this).hasClass('active') || !$(this).hasClass('locked')) {
                 console.log($(this));

                var v = x * (parseInt($(this).attr('data-percent')) / y);
                $(this).width(v + '%');
                $(this).find('.value').text(Math.round(v) + '%');
                $(this).find('.value_in').val(Math.round(v));

              }
            });

          },

          slideEnd: function() {
            // kill the events on mouse up.
            _this.target.parent().removeClass('active');
            $(this).off('mousemove', slider.slideMove);
            $(this).off('mouseup', slider.slideEnd);
          },
        }

        return Slider;

      }());

    </script>

</head>
<body>
    <div class="chat-app-wrapper">
        <nav>
            <div class="nav-left-section">
                <span id="title">Preffered learning style determination</span>
            </div><br>
            <div class="" style="float:right;">
              <form class="" action="{% url 'home:revisit' %}" method="GET">
                {% csrf_token %}
                <button type="submit" name="revisit" style="width:130%;height:1%;color:white;">Revisit Later?</button>
              </form>

            </div>
        </nav>





        <div class="chat">

          <center>
            <div class="" style="width:55%;">
              <center>
                <br>
                <div class="progress" style="width:65%;border:0.5px solid rgb(200,200,200);">
                  <div class="progress-bar progress-bar-success" role="progressbar" style="width:{{pa}}%">
                    Answered {{pa}}%
                  </div>
                  <div class="progress-bar progress-bar-warning" role="progressbar" style="width:{{pu}}%">
                    Unanswered {{pu}}%
                  </div>
                  <br>
                </div>

                <span style="color:rgb(0,0,0)">{{ progress }}% Complete</span>
              </center><br>
              <center>
                <div class="progress" style="width:65%;border:0.5px solid rgb(200,200,200);">
                  <div class="progress-bar progress-bar-info progress-bar-striped" role="progressbar" aria-valuenow={{ progress2 }} aria-valuemin="0" aria-valuemax="100" style="width:{{ progress2 }}%;">

                  </div>
                </div>
                <span style="color:rgb(0,0,0)">{{ progress2 }}% Complete</span>
              </center>
            </div>
          </center>


          <br>
            <div class="container">
                <div class="msg-header">
                    <div class="active">
                        <h5>
                          Q{{q}}
                        </h5>
                    </div>
                </div>

                <div class="chat-page">
                    <div class="msg-inbox">
                        <div class="chats" id="chats">
                            <div class="msg-page" id="msg-page">
                                <div class="loading-message-container" id="loading-message-container" style="display: none;">
                                    <div class="spinner">
                                            <svg width="100" height="100" viewBox="0 0 38 38" xmlns="http://www.w3.org/2000/svg" stroke="#003">
                                                <g fill="none" fill-rule="evenodd">
                                                  <g transform="translate(1 1)" stroke-width="2">
                                                    <circle stroke-opacity=".5" cx="18" cy="18" r="18"></circle>
                                                    <path d="M36 18c0-9.94-8.06-18-18-18">
                                                      <animateTransform attributeName="transform" type="rotate" from="0 18 18" to="360 18 18" dur="1s" repeatCount="indefinite"></animateTransform>
                                                    </path>
                                                  </g>
                                                </g>
                                              </svg>
                                    </div>
                                </div>


                                <div>
                                    <div id="group-message-holder" style="">

<!--  ############################################# -->


<!--  ############################################# -->
                            <div class="w3-container" style='width:60%; float:center;'>
                              <form class="" action="{% url 'home:quiz2' %}" method="POST">
                                {% csrf_token %}
                                  {{ content }}
                              </form>
                            </div>

                            <form class="" action="{% url 'home:quiz2' %}" method="POST">
                              {% csrf_token %}
                                {{ exit }}
                            </form>

<!--  ############################################# -->

                </div>
                    </div>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
                <br><br>

            </div>
        </div>
    </div>



<!-- Dummy scripts -->
<!-- <script src="{% static 'home/js/chatService-dummy.js' %}"></script>
<script src="{% static 'home/js/script-dummy.js' %}"></script> -->


</body></html>